[env:d1_mini]
platform      = espressif8266
board         = d1_mini
framework     = arduino

board_build.filesystem = littlefs
monitor_speed  = 115200
upload_speed   = 921600

lib_deps =
    esp32async/ESPAsyncWebServer @ ^3.7
    knolleary/PubSubClient       @ ^2.8
    bblanchon/ArduinoJson        @ ^7.0

build_flags =
    -D MQTT_MAX_PACKET_SIZE=512
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY
    -Os
    -Wno-sign-compare